server:
  port: 8080

spring:
    datasource:
      name: springboot
      type: com.alibaba.druid.pool.DruidDataSource
      #druid\u76F8\u5173\u914D\u7F6E
      druid:
        #\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters
        filter: stat
        #mysql\u9A71\u52A8
        driver-class-name: com.mysql.cj.jdbc.Driver
        #\u57FA\u672C\u5C5E\u6027
        url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: ycz123456
        #\u914D\u7F6E\u521D\u59CB\u5316\u5927\u5C0F/\u6700\u5C0F/\u6700\u5927
        initial-size: 1
        min-idle: 1
        max-active: 20
        #\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
        max-wait: 60000
        #\u95F4\u9694\u591A\u4E45\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5
        time-between-eviction-runs-millis: 60000

    thymeleaf:
      cache: false

     #spring-aop\u914D\u7F6E
    aop:
     #\u542F\u7528@Aspectj\u6CE8\u89E3\u9A71\u52A8\u7684\u5207\u9762\uFF0C\u5141\u8BB8Spring\u521B\u5EFA\u57FA\u4E8E\u7C7B\u7684\u4EE3\u7406
      auto: true
      proxy-target-class: true
    mvc:
      static-path-pattern: /static/**

# \u8BE5\u914D\u7F6E\u8282\u70B9\u4E3A\u72EC\u7ACB\u7684\u8282\u70B9\uFF0C\u6709\u5F88\u591A\u540C\u5B66\u5BB9\u6613\u5C06\u8FD9\u4E2A\u914D\u7F6E\u653E\u5728spring\u7684\u8282\u70B9\u4E0B\uFF0C\u5BFC\u81F4\u914D\u7F6E\u65E0\u6CD5\u88AB\u8BC6\u522B
mybatis:
  mapper-locations: classpath:mapper/*.xml  #\u6CE8\u610F\uFF1A\u4E00\u5B9A\u8981\u5BF9\u5E94mapper\u6620\u5C04xml\u6587\u4EF6\u7684\u6240\u5728\u8DEF\u5F84
#  type-aliases-package: cn.ycz.po # \u6CE8\u610F\uFF1A\u5BF9\u5E94\u5B9E\u4F53\u7C7B\u7684\u8DEF\u5F84


logging:
  #\u914D\u7F6E\u65E5\u5FD7\u6587\u4EF6\u8DEF\u5F84
  path: G:\myblog_log\log
  level:
    xatu.zsl: debug #\u4E0D\u540C\u76EE\u5F55\u4E0B\u7684\u65E5\u5FD7\u53EF\u914D\u7F6E\u4E0D\u540C\u7EA7\u522B
    org.springfromework.web: info
    org.hibernate: error